const lang = {
  en: {
    search: "Search",
    searching: "Searching",
    gptSearchTitle: "Find your next favourite",
    gptSearchSubtitle:
      "Describe what you're in the mood for — we'll do the rest.",
    gptSearchPlaceholder: "What would you like to watch today?",
    refineTaste: "Refine my taste",
    clearAll: "Clear all",
    genreLabel: "Genre",
    moodLabel: "Mood",
    eraLabel: "Era",
    avoidLabel: "Not in the mood for",
    errorGeneric: "Something went wrong. Please try again.",
    errorNetwork: "Can't reach the recommendation service. Is it running?",
    errorRateLimited: "Too many searches. Please wait a moment.",
    errorNoResults: "No suggestions found. Try rephrasing your search.",
  },
  hindi: {
    search: "खोज",
    searching: "खोज रहे हैं",
    gptSearchTitle: "अपनी अगली पसंदीदा फ़िल्म खोजें",
    gptSearchSubtitle: "बताइए आपका मूड क्या है — बाकी हम संभाल लेंगे।",
    gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
    refineTaste: "मेरी पसंद बताएं",
    clearAll: "सब हटाएं",
    genreLabel: "शैली",
    moodLabel: "मूड",
    eraLabel: "दौर",
    avoidLabel: "यह नहीं चाहिए",
    errorGeneric: "कुछ गड़बड़ हो गई। कृपया पुनः प्रयास करें।",
    errorNetwork: "सेवा से संपर्क नहीं हो पा रहा। क्या यह चालू है?",
    errorRateLimited: "बहुत अधिक खोजें। कृपया थोड़ा रुकें।",
    errorNoResults: "कोई सुझाव नहीं मिला। खोज बदलकर देखें।",
  },
  spanish: {
    search: "Buscar",
    searching: "Buscando",
    gptSearchTitle: "Encuentra tu próxima favorita",
    gptSearchSubtitle: "Dinos qué te apetece ver — nosotros hacemos el resto.",
    gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
    refineTaste: "Afinar mis gustos",
    clearAll: "Borrar todo",
    genreLabel: "Género",
    moodLabel: "Ánimo",
    eraLabel: "Época",
    avoidLabel: "Nada de esto",
    errorGeneric: "Algo salió mal. Inténtalo de nuevo.",
    errorNetwork: "No se puede conectar con el servicio. ¿Está activo?",
    errorRateLimited: "Demasiadas búsquedas. Espera un momento.",
    errorNoResults: "Sin sugerencias. Prueba a reformular tu búsqueda.",
  },
};

export default lang;
